version: '3.8'

services:
  ntopng:
    image: ntop/ntopng:latest
    container_name: ntopng
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - NTOPNG_CONFIG_FILE=/etc/ntopng/ntopng.conf
    volumes:
      - ./config/ntopng.conf:/etc/ntopng/ntopng.conf:ro
      - ./config/categories.txt:/etc/ntopng/categories.txt:ro
      - ./config/alerts.conf:/etc/ntopng/alerts.conf:ro
      - ./data:/var/lib/ntopng
      - /var/log/ntopng:/var/log/ntopng
    ports:
      - "3001:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
