version: '3.8'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "67:67/udp"    # DHCP server
      - "68:68/udp"    # DHCP client
    environment:
      TZ: ${TZ:-America/New_York}
      WEBPASSWORD: ${PIHOLE_PASSWORD:-}
      SERVERIP: ${SERVER_IP}
      DNS1: ${DNS1:-1.1.1.1}
      DNS2: ${DNS2:-1.0.0.1}
      DNSMASQ_LISTENING: ${DNSMASQ_LISTENING:-local}
      DNSMASQ_USER: pihole
      INTERFACE: ${INTERFACE:-eth0}
      VIRTUAL_HOST: ${VIRTUAL_HOST:-pihole.local}
      IPv6: ${IPV6:-false}
      TEMPERATUREUNIT: ${TEMPERATURE_UNIT:-c}
      WEBUIBOXEDLAYOUT: traditional
      REV_SERVER: ${REV_SERVER:-false}
      REV_SERVER_TARGET: ${REV_SERVER_TARGET:-192.168.3.1}
      REV_SERVER_DOMAIN: ${REV_SERVER_DOMAIN:-local}
      REV_SERVER_CIDR: ${REV_SERVER_CIDR:-192.168.3.0/24}
      DNSSEC: ${DNSSEC:-true}
      CONDITIONAL_FORWARDING: ${CONDITIONAL_FORWARDING:-true}
      CONDITIONAL_FORWARDING_IP: ${CONDITIONAL_FORWARDING_IP:-192.168.3.1}
      CONDITIONAL_FORWARDING_DOMAIN: ${CONDITIONAL_FORWARDING_DOMAIN:-local}
      CONDITIONAL_FORWARDING_REVERSE: ${CONDITIONAL_FORWARDING_REVERSE:-3.168.192.in-addr.arpa}
    volumes:
      - /mnt/storage/pi_hole_data/etc-pihole:/etc/pihole
      - /mnt/storage/pi_hole_data/etc-dnsmasq.d:/etc/dnsmasq.d
      - ./config/custom.list:/etc/pihole/custom.list:ro
      - ./config/adlists.list:/etc/pihole/adlists.list:ro
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      - monitoring_network
    healthcheck:
      test: ["CMD", "dig", "@127.0.0.1", "google.com"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    dns:
      - 127.0.0.1
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    network_mode: "host"  # Required for DHCP to work properly

networks:
  monitoring_network:
    name: monitoring_network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
